### ISSUE TITLE
Nested conversation.ask() don't fire

### ISSUE THREAD

**Issue by andrijdavid** [Charca/bootbot#11] opened 2016-09-05 18:47 UTC
Hello,

When i execute this code , the program get stucked on the second recursion of getResponse().
Both  someFunctionWhoGenerateResponse and generateGreeting function return valid string and work perfectly.

`
const bot = new BootBot({
    accessToken: config.get('accessToken'),
    verifyToken: config.get('verifyToken'),
    appSecret: config.get('appSecret')
});

function getResponse(txt, convo) {
    var rps = someFunctionWhoGenerateResponse(txt);
    convo.sendTypingIndicator();
    convo.ask(rps, (payload, convo, data) => {
        convo.say("hum");
        getResponse(payload.message.text, convo);
    });
}

function sendGreeting(response, convo) {
    var init = generateGreeting();
    convo.ask(init, (payload, convo, data) => {
        getResponse(payload.message.text, convo);
    });
}

bot.hear('hello', (payload, chat) => {
   chat.conversation((convo)=> {
        sendGreeting(payload.message.text, convo);
    });
});
`

**Comment by Charca** [comment] 2016-09-06 17:51
Hey @andrijdavid ,

I don't see anything wrong with the code except there's no way to get out of the `getResponse` loop. If that's the problem then you just need to call `convo.end()` if a certain condition passes instead of calling getResponse again.

If the problem is that the program actually dies when getResponse is called a second time, then it's probably something else. Do you see any errors in the console when this happens? If you console.log a message in the getResponse function, do you see the message logging multiple times before the process dies?

**Comment by hudgins** [comment] 2016-12-19 16:49
@Charca I think there's a small bug here that might be related to this issue:

https://github.com/Charca/bootbot/blob/master/lib/Conversation.js#L105

If you synchronously call ask() again inside the listener, your callback is assigned to this.listeningAnswer, but upon return to the above line of code, your newly added listener is thrown away. This was causing a similar issue for me and changing it to do something more like:

      const listeningAnswer = this.listeningAnswer
      this.listeningAnswer = null
      listeningAnswer.apply(this, [ payload, this, data]) // eslint-disable-line

solved the problem. I can make a pull request at some point but am kinda in a crunch at the moment.

Thanks for the very nice library!

@andrijdavid Heads up, FYI.

**Comment by Charca** [comment] 2016-12-21 21:31
Hey @hudgins, thanks for spotting this issue. Feel free to submit a PR and I'll take a look/test it afterwards.

**Comment by andrijdavid** [comment] 2017-02-19 05:48
Thanks @hudgins.

2016-12-22 1:01 GMT+03:30 Maxi Ferreira <notifications@github.com<mailto:notifications@github.com>>:

Hey @hudgins<https://github.com/hudgins>, thanks for spotting this issue. Feel free to submit a PR and I'll take a look/test it afterwards.

**Comment by Charca** [comment] 2017-03-28 05:24
Fixed in v1.0.10: https://github.com/Charca/bootbot/compare/v1.0.9...v1.0.10

**Closed by Charca** 2017-03-28 05:24 UTC
