### ISSUE TITLE
BootBot.js: TypeError: Cannot read property 'forEach' of undefined 

### ISSUE THREAD

**Issue by ProfNandaa** [Charca/bootbot#38] opened 2017-04-25 18:01 UTC
**`tag: needs-investigation`**

Once in awhile, I get this error in my logs, but I can't seem to find the cause:
```
TypeError: Cannot read property 'forEach' of undefined at data.entry.forEach(/app/node_modules/bootbot/lib/BootBot.js:408:24) 
```

I'll update if I get it.

**Comment by hkalexling** [comment] 2017-08-01 15:06
I was having the same issue. The problem is [here](https://github.com/Charca/bootbot/blob/master/lib/BootBot.js#L410):

```js
// Iterate over each entry. There may be multiple if batched.
data.entry.forEach((entry) => {
    // Iterate over each messaging event
    entry.messaging.forEach((event) => {
    // ...
    }
}
```

For some reasons, the `entry` object from the webhook may not contain the `messaging` property and thus trigger the error. Simply editing the source code to make sure the `messaging` property exists works for me.

```js
// Iterate over each entry. There may be multiple if batched.
data.entry.forEach((entry) => {
    // Iterate over each messaging event
    if (entry.messaging) {
        entry.messaging.forEach((event) => {
            // ...
        }
    }
}
```

**Comment by mraaroncruz** [comment] 2017-08-25 05:28
I only think this is a proper solution if it is a facebook bug. Otherwise we're missing a message type that we should be dealing with in a different branch.

Can you tell us more about what the faulty message looks like @ProfNandaa or @hkalexling or @KhanMaytok?

**Comment by ProfNandaa** [comment] 2017-09-07 04:59
@mraaroncruz - I'll try reproduce and get back, but I think you are right, it might be from the Messenger side, coz it was happening **once in awhile**.

**Comment by FnTm** [comment] 2017-11-06 19:15
@mraaroncruz this is a message that triggered this notice for me:
```
{ object: 'page',
  entry: 
   [ { id: '1627653683954046',
       time: 1509995621217,
       standby: 
        [ { recipient: { id: '1627653683954046' },
            timestamp: 1509995621217,
            sender: { id: '1193950450705282' },
            postback: { title: 'Nē' } } ] } ] }
```
The interesting thing here is that everything still works fine, and I can continue the conversation without a problem.

**Comment by FnTm** [comment] 2017-11-08 18:46
Update: if you only want to stop receiving these errors there is a simple way to do that:

1. Go to you App Settings
2. Messenger -> Settings -> Edit Events (on Webhooks section header) and uncheck `standby`

No more TypeErrors, which is what I was after in my case.

**Comment by mraaroncruz** [comment] 2017-11-25 14:42
Closing to add a more specific issue. https://github.com/Charca/bootbot/issues/86

**Closed by mraaroncruz** 2017-11-25 14:42 UTC
