### ISSUE TITLE
How to communicate with different pages with the same app

### ISSUE THREAD

**Issue by MMayla** [Charca/bootbot#42] opened 2017-05-17 15:35 UTC
I want to make generic bot the can communicate with different pages knowing from which page the message received and response to the user in that specific page.

For knowing which page I think It can be done easily from the recipient attribute like this
```
bot.on('message', (payload, chat) => {
switch(payload.recipient) {
  case '12334784': //page id
    // do something
    break;
  case '9877654': //page id
    // do something
    break;
}
});
```
But in the first place BootBot accept only one `page access token`

```
const bot = new BootBot({
  accessToken: 'PAGE_ACCESS_TOKEN',
  verifyToken: 'FB_VERIFY_TOKEN',
  appSecret: 'FB_APP_SECRET'
});
```

What is the best way to accomplish such thing? How to accept messages from different pages?

**Comment by pferdefleisch** [comment] 2017-05-23 08:53
Bootbot makes some assumptions that will make your usecase difficult as the codebase stands.

The simplest way I could think to do this is to create your own express endpoint and two bots, then proxy the request to the correct bot after checking for the recipient id, like you show above. The problem is that, at the moment:

- bootbot [hardcodes the webhook path](https://github.com/Charca/bootbot/blob/master/lib/BootBot.js#L399)
- the message handler is [part of the route definition](https://github.com/Charca/bootbot/blob/master/lib/BootBot.js#L406-L435) so you can't exactly proxy to it without copying a bunch of code

So if this message handling code was removed from the route handler, you could:

- Create your own express app - make sure your webhook is not on /webhook
- Create a bot for each page
- Check the recipient id and delegate the message to the message handler (doesn't exist yet) of the appropriate bot
- profit

If I have time, I'll consider a pull request that pulls this stuff out since it looks like @Charca's pretty busy at the moment.

Or hopefully someone has a way better idea of something simple that I've missed.

**Comment by MMayla** [comment] 2017-05-23 18:56
@pferdefleisch this works fine with me

**Comment by tmwd** [comment] 2017-05-28 19:12
Would it be easier if we refactor code to make possible to pass the 'route' param to each Bot instance?
Alike:
```
const bot = new BootBot({
  accessToken: 'PAGE_ACCESS_TOKEN',
  verifyToken: 'FB_VERIFY_TOKEN',
  appSecret: 'FB_APP_SECRET',
  webhook: '/webhook'
});
```
So each instance could listen their own route for webhooks.

**Comment by Robophil** [comment] 2017-06-06 13:39
that would be really nice @tmwd

**Comment by mraaroncruz** [comment] 2017-11-25 14:35
@tmwd's suggestion was implemented in #53 and there is an open PR for my suggestion above. I will close this now. Maybe someday we will have page routing but I don't see it in the near future.
Please open an issue specific to page routing if you still think it is a needed feature @MMayla.
Cheers

**Closed by mraaroncruz** 2017-11-25 14:35 UTC

**Comment by dimitri-gigot** [comment] 2018-04-10 14:45
Hello,
I know this issue is "closed" but today we had the same issue at the office.

So i wrote some code and manage to make it work.
I didn't change a line in the Bootbot library but i wrote a "wrapper" around it.

If you guys still interested in that,  i can refactor my code and make it available on Github.

Cheers

**Comment by mraaroncruz** [comment] 2018-04-10 16:56
If it wouldn't be a lot of work, I think some people would be really interested.
Otherwise, I'd wait for a couple people to speak up.
Great you got it working @dimitri-gigot!

**Comment by dimitri-gigot** [comment] 2018-04-10 17:03
Oups.. I removed my previous comment (miss click)  :( 

I actually have to refactor the code because I make it "dirty" this afternoon and I can't obviously deploy that.
I'll link my code when it will be done ;)
